// <auto-generated />
using System;
using CodeWithMe.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeWithMe.Core.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20260425025657_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CodeWithMe.Core.Models.Period", b =>
                {
                    b.Property<string>("PeriodId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("period_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Day")
                        .HasColumnType("int")
                        .HasColumnName("day");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<string>("EventId")
                        .HasColumnType("longtext")
                        .HasColumnName("event_id");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("period_type");

                    b.Property<string>("SchoolId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("school_id");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("PeriodId");

                    b.HasIndex("SchoolId");

                    b.ToTable("periods");
                });

            modelBuilder.Entity("CodeWithMe.Core.Models.School", b =>
                {
                    b.Property<string>("SchoolId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("school_id");

                    b.Property<int>("ClassDurationInMinutes")
                        .HasColumnType("int")
                        .HasColumnName("class_duration");

                    b.Property<TimeSpan>("ClassEndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("class_end_time");

                    b.Property<TimeSpan>("ClassStartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("class_start_time");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("FirstBreakDurationInMinutes")
                        .HasColumnType("int")
                        .HasColumnName("first_break_duration");

                    b.Property<TimeSpan>("FirstBreakStartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("first_break_start_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("school_type");

                    b.Property<int?>("SecondBreakDurationInMinutes")
                        .HasColumnType("int")
                        .HasColumnName("second_break_duration");

                    b.Property<TimeSpan?>("SecondBreakStartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("second_break_start_time");

                    b.Property<int?>("ThirdBreakDurationInMinutes")
                        .HasColumnType("int")
                        .HasColumnName("third_break_duration");

                    b.Property<TimeSpan?>("ThirdBreakStartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("third_break_start_time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("SchoolId");

                    b.ToTable("schools");
                });

            modelBuilder.Entity("CodeWithMe.Core.Models.Period", b =>
                {
                    b.HasOne("CodeWithMe.Core.Models.School", null)
                        .WithMany("Periods")
                        .HasForeignKey("SchoolId");
                });

            modelBuilder.Entity("CodeWithMe.Core.Models.School", b =>
                {
                    b.Navigation("Periods");
                });
#pragma warning restore 612, 618
        }
    }
}
