// <auto-generated />
using System;
using CodeWithMe.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeWithMe.Core.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20260410053456_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CodeWithMe.Core.Models.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subject_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("subject_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("SubjectId");

                    b.ToTable("CWM_Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
